import { detectProductTag, type ProductTag } from "./productCategories";

export interface BlogArticle {
  slug: string;
  title: string;
  description: string;
  date: string;
  image: string;
  routePath: string;
  productTag?: ProductTag;
}

export const blogArticles: BlogArticle[] = [
  // === Бывшие динамические статьи, теперь статические ===
  {
    slug: "morskoy-ezh-5-mifov-i-vsya-pravda-o-glavnom-delikatese-sahalina-2026-04-17",
    title: "Морской ёж: 5 мифов и вся правда о главном деликатесе Сахалина",
    description: "Пять популярных мифов о морском еже и правда о нём: вкус, польза икры, свежесть и как его правильно есть.",
    date: "2026-04-17",
    image: "/src/assets/blog-urchin-1.jpg",
    routePath: "/blog/morskoy-ezh-5-mifov-i-vsya-pravda-o-glavnom-delikatese-sahalina-2026-04-17",
    productTag: "urchin" as ProductTag,
  },
  {
    slug: "morskoy-ezh-s-sahalina-iskusstvo-podachi-i-idealnye-vinnye-pary-2026-04-22",
    title: "Морской ёж с Сахалина: искусство подачи и идеальные винные пары",
    description: "Как красиво подать морского ежа и с каким вином сочетать. Идеальные пары к икре морского ежа.",
    date: "2026-04-22",
    image: "/src/assets/blog-urchin-2.jpg",
    routePath: "/blog/morskoy-ezh-s-sahalina-iskusstvo-podachi-i-idealnye-vinnye-pary-2026-04-22",
    productTag: "urchin" as ProductTag,
  },
  {
    slug: "sahalinskiy-morskoy-ezh-chem-on-luchshe-yaponskih-i-chiliyskih-analogov-2026-04-21",
    title: "Сахалинский морской ёж: чем он лучше японских и чилийских аналогов",
    description: "Честное сравнение сахалинского морского ежа с японским и чилийским: свежесть, вкус, логистика и цена.",
    date: "2026-04-21",
    image: "/src/assets/blog-urchin-3.jpg",
    routePath: "/blog/sahalinskiy-morskoy-ezh-chem-on-luchshe-yaponskih-i-chiliyskih-analogov-2026-04-21",
    productTag: "urchin" as ProductTag,
  },
  {
    slug: "ustricy-dlya-detoksa-i-diety-polza-sahalinskih-mollyuskov-2026-04-19",
    title: "Устрицы для лёгкого рациона: польза сахалинских моллюсков",
    description: "Чем полезны сахалинские устрицы: много белка и цинка при низкой калорийности. Как включить в меню.",
    date: "2026-04-19",
    image: "/src/assets/blog-oysters-real-1.jpg",
    routePath: "/blog/ustricy-dlya-detoksa-i-diety-polza-sahalinskih-mollyuskov-2026-04-19",
    productTag: "oysters" as ProductTag,
  },
  {
    slug: "sahalinskiy-grebeshok-kak-vklyuchit-v-dietu-i-programmu-detoks-2026-04-23",
    title: "Сахалинский гребешок в лёгком рационе: белок без лишних калорий",
    description: "Как включить гребешок в лёгкое меню: чистый белок при низкой калорийности, минералы и быстрая готовка.",
    date: "2026-04-23",
    image: "/src/assets/blog-scallop-real.jpg",
    routePath: "/blog/sahalinskiy-grebeshok-kak-vklyuchit-v-dietu-i-programmu-detoks-2026-04-23",
    productTag: "scallop" as ProductTag,
  },
  {
    slug: "vongole-ili-petushki-v-chem-raznica-i-kak-vybrat-luchshie-mollyuski-2026-04-18",
    title: "Вонголе или петушки: в чём разница и как выбрать лучшие моллюски",
    description: "Вонголе и петушки: в чём разница между моллюсками, как отличить и выбрать свежих. Понятный гид.",
    date: "2026-04-18",
    image: "/src/assets/blog-vongole-real-1.jpg",
    routePath: "/blog/vongole-ili-petushki-v-chem-raznica-i-kak-vybrat-luchshie-mollyuski-2026-04-18",
    productTag: "vongole" as ProductTag,
  },
  // === Мохнаторукий краб (опт) ===
  {
    slug: "mohnatorukij-krab-optom",
    title: "Мохнаторукий краб оптом с Сахалина: живые поставки для ресторанов",
    description: "Оптовые поставки живого мохнаторукого краба с Сахалина. Калибровка партий по размеру, доставка живым в термобоксе, документы.",
    date: "2026-07-22",
    image: "/src/assets/blog-hairy-crab-underwater.jpg",
    routePath: "/blog/mohnatorukij-krab-optom",
    productTag: "hairy-crab" as ProductTag,
  },
  {
    slug: "zhivoj-mohnatorukij-krab-dostavka",
    title: "Доставка живого мохнаторукого краба по России: как мы возим его живым",
    description: "Передержка, кислородная упаковка, термобокс, сроки 24-48 часов и документы. Как довезти живого краба через всю страну.",
    date: "2026-07-22",
    image: "/src/assets/product-hairy-crab.jpg",
    routePath: "/blog/zhivoj-mohnatorukij-krab-dostavka",
    productTag: "hairy-crab" as ProductTag,
  },
  {
    slug: "chto-takoe-mohnatorukij-krab",
    title: "Что такое мохнаторукий краб: волосатый, шанхайский, ради чего его берут",
    description: "Как выглядит, почему «мохнаторукий», какого размера бывает, когда сезон и как его берут. Понятный гид поставщика с Сахалина.",
    date: "2026-07-22",
    image: "/src/assets/blog-hairy-crab-cooked.jpg",
    routePath: "/blog/chto-takoe-mohnatorukij-krab",
    productTag: "hairy-crab" as ProductTag,
  },

  {
    slug: "mohnatorukij-krab-iz-reki-v-more",
    title: "Краб, который живёт в реке: маршруты мохнаторукого краба от Амура до Сахалина",
    description: "Мохнаторукий краб поднимается по рекам на десятки километров и возвращается к морю. Ареал, срок жизни, чем питается.",
    date: "2026-09-13",
    image: "/src/assets/crab-photo-7.jpg",
    routePath: "/blog/mohnatorukij-krab-iz-reki-v-more",
    productTag: "hairy-crab" as ProductTag,
  },
  {
    slug: "mohnatorukij-krab-v-evrope",
    title: "Деликатес у нас, стихийное бедствие в Европе: история мохнаторукого краба",
    description: "Балластная вода, 1912 год, 700 км вверх по Эльбе и десятки миллионов евро ущерба. И почему на Дальнем Востоке всё наоборот.",
    date: "2026-09-13",
    image: "/src/assets/crab-photo-8.jpg",
    routePath: "/blog/mohnatorukij-krab-v-evrope",
    productTag: "hairy-crab" as ProductTag,
  },
  {
    slug: "yaponskiy-ili-kitayskiy-mohnatorukij-krab",
    title: "Японский или китайский: какой мохнаторукий краб добывается на Дальнем Востоке",
    description: "Два похожих вида, один промысловый ареал. Размеры, промысловый размер от 5 см и молодой промысел с 1998 года.",
    date: "2026-09-13",
    image: "/src/assets/crab-photo-2.jpg",
    routePath: "/blog/yaponskiy-ili-kitayskiy-mohnatorukij-krab",
    productTag: "hairy-crab" as ProductTag,
  },

  {
    slug: "kak-gotovit-mohnatorukogo-kraba",
    title: "Как готовить мохнаторукого краба: пар против варки и почему нельзя сырым",
    description: "Почему живого краба не бросают в кипяток, зачем пар вместо варки, сколько держать и при какой температуре.",
    date: "2026-09-13",
    image: "/src/assets/crab-photo-1.jpg",
    routePath: "/blog/kak-gotovit-mohnatorukogo-kraba",
    productTag: "hairy-crab" as ProductTag,
  },
  {
    slug: "sup-iz-mohnatorukogo-kraba",
    title: "Кани-маки-дзиру: японский суп, в котором краба толкут вместе с панцирем",
    description: "Деревенский рецепт из Миядзаки: краба разбивают целиком, процеживают и варят густой суп на мисо.",
    date: "2026-09-13",
    image: "/src/assets/crab-photo-3.jpg",
    routePath: "/blog/sup-iz-mohnatorukogo-kraba",
    productTag: "hairy-crab" as ProductTag,
  },
  {
    slug: "shanhajskaya-podacha-mohnatorukogo-kraba",
    title: "Шанхайская классика: краб на пару с соусом из чёрного уксуса и имбиря",
    description: "Как подают мохнаторукого краба в Китае: пар, тёплый соус на чёрном уксусе, порядок разбора.",
    date: "2026-09-13",
    image: "/src/assets/crab-photo-6.jpg",
    routePath: "/blog/shanhajskaya-podacha-mohnatorukogo-kraba",
    productTag: "hairy-crab" as ProductTag,
  },

  {
    slug: "zhivoj-grebeshok-v-moskve",
    title: "Живой морской гребешок в Москве: как заказать напрямую с Сахалина",
    description: "Где в Москве взять живого гребешка, за сколько он доезжает и чем прямая поставка отличается от перекупщиков.",
    date: "2026-09-13",
    image: "/src/assets/blog-scallop-photo-1.jpg",
    routePath: "/blog/zhivoj-grebeshok-v-moskve",
    productTag: "scallop" as ProductTag,
  },
  {
    slug: "dostavka-grebeshka-v-moskvu",
    title: "Доставка живого гребешка в Москву: сроки, рейс, упаковка",
    description: "Прямой авиарейс с Сахалина, 24-48 часов, термобокс с хладагентом и что делать сразу после получения.",
    date: "2026-09-13",
    image: "/src/assets/blog-scallop-photo-9.jpg",
    routePath: "/blog/dostavka-grebeshka-v-moskvu",
    productTag: "scallop" as ProductTag,
  },
  {
    slug: "grebeshok-optom-moskva",
    title: "Гребешок оптом для ресторана в Москве: поставка напрямую с Сахалина",
    description: "Ровный калибр, объём по графику, холодовая цепь и ветеринарные документы. Прайс в день обращения.",
    date: "2026-09-13",
    image: "/src/assets/blog-scallop-photo-8.jpg",
    routePath: "/blog/grebeshok-optom-moskva",
    productTag: "scallop" as ProductTag,
  },

  {
    slug: "ustritsy-yuzhno-sahalinsk",
    title: "Где купить свежие устрицы в Южно-Сахалинске",
    description: "Живые сахалинские устрицы в городе: цена, размер, самовывоз со склада и доставка. Как отличить живую устрицу.",
    date: "2026-09-13",
    image: "/src/assets/blog-oyster-photo-2.jpg",
    routePath: "/blog/ustritsy-yuzhno-sahalinsk",
    productTag: "oysters" as ProductTag,
  },
  {
    slug: "chto-poprobovat-na-sahaline",
    title: "Что попробовать из морепродуктов на Сахалине: гид для гостя острова",
    description: "Устрицы, гребешок, вонголе, морской ёж и мохнаторукий краб: что стоит попробовать на острове и когда сезон.",
    date: "2026-09-13",
    image: "/src/assets/blog-oyster-photo-1.jpg",
    routePath: "/blog/chto-poprobovat-na-sahaline",
    productTag: "oysters" as ProductTag,
  },
  {
    slug: "uvezti-moreprodukty-s-sahalina",
    title: "Как увезти морепродукты с Сахалина: упаковка, сроки и перелёт",
    description: "Термобокс, хладагент, сроки жизни моллюска в дороге, документы и что уточнить у авиакомпании.",
    date: "2026-09-13",
    image: "/src/assets/blog-scallop-photo-9.jpg",
    routePath: "/blog/uvezti-moreprodukty-s-sahalina",
    productTag: "scallop" as ProductTag,
  },
  // === Морской ёж ===
  {
    slug: "morskoj-ezh-sahalin",
    title: "Сахалинский морской ёж: что это за деликатес и почему он так ценится",
    description: "Разбираемся, чем так хорош сахалинский морской ёж. Рассказываем про вкус, пользу, способы добычи и почему он считается одним из лучших в мире.",
    date: "2026-04-12",
    image: "/src/assets/blog-urchin-1.jpg",
    routePath: "/blog/morskoj-ezh-sahalin",
  },
  {
    slug: "kak-vybrat-morskogo-ezha",
    title: "Как выбрать свежего морского ежа: советы от поставщика с Сахалина",
    description: "На что смотреть при покупке живого морского ежа. Признаки свежести, правила хранения и частые ошибки покупателей.",
    date: "2026-04-12",
    image: "/src/assets/blog-urchin-2.jpg",
    routePath: "/blog/kak-vybrat-morskogo-ezha",
  },
  {
    slug: "polza-morskogo-ezha",
    title: "Польза морского ежа: состав и свойства для здоровья",
    description: "Честный обзор полезных свойств икры морского ежа. Витамины, минералы, омега-3 и легендарный эхинохром А в деталях.",
    date: "2026-04-12",
    image: "/src/assets/blog-urchin-3.jpg",
    routePath: "/blog/polza-morskogo-ezha",
  },
  // === Морской гребешок ===
  {
    slug: "morskoj-grebeshok-sahalin",
    title: "Сахалинский морской гребешок: королевский деликатес Дальнего Востока",
    description: "Всё про морской гребешок с Сахалина: происхождение, вкус, текстура, польза и из чего складывается цена.",
    date: "2026-04-12",
    image: "/src/assets/blog-scallop-royal.jpg",
    routePath: "/blog/morskoj-grebeshok-sahalin",
  },
  {
    slug: "kak-prigotovit-grebeshok",
    title: "Как приготовить морской гребешок дома: рецепты от шеф-поваров",
    description: "Пошаговые способы приготовления сахалинского гребешка. Обжарка, гриль, карпаччо или паста: выбирайте свой вариант.",
    date: "2026-04-12",
    image: "/src/assets/blog-scallop-card-1.jpg",
    routePath: "/blog/kak-prigotovit-grebeshok",
  },
  {
    slug: "kak-vybrat-grebeshok",
    title: "Как выбрать свежий морской гребешок: советы от профи с острова",
    description: "На что обращать внимание: свежий или замороженный, главные признаки качества и правила хранения.",
    date: "2026-04-12",
    image: "/src/assets/blog-scallop-choose.jpg",
    routePath: "/blog/kak-vybrat-grebeshok",
  },
  {
    slug: "zhivoj-morskoj-grebeshok-sahalin",
    title: "Живой морской гребешок с Сахалина: почему это лучший выбор",
    description: "Чем живой сахалинский гребешок отличается от заморозки. Вкус, текстура, польза и детали прямой поставки.",
    date: "2026-04-25",
    image: "/src/assets/blog-scallop-live-hero.jpg",
    routePath: "/blog/zhivoj-morskoj-grebeshok-sahalin",
  },
  {
    slug: "kak-hranit-zhivogo-grebeshka",
    title: "Как хранить живого морского гребешка дома: пошаговый план",
    description: "Сроки и температура хранения, признаки свежести и что делать, если решили заморозить.",
    date: "2026-04-25",
    image: "/src/assets/blog-scallop-live-storage.jpg",
    routePath: "/blog/kak-hranit-zhivogo-grebeshka",
  },
  {
    slug: "dostavka-zhivogo-grebeshka-rossiya",
    title: "Доставка живого морского гребешка с Сахалина по России",
    description: "Как мы привозим живой деликатес в Москву, Петербург и регионы за 24-48 часов. Упаковка, документы и гарантии.",
    date: "2026-04-25",
    image: "/src/assets/blog-scallop-live-delivery.jpg",
    routePath: "/blog/dostavka-zhivogo-grebeshka-rossiya",
  },
  // === Вонголе ===
  {
    slug: "chto-takoe-vongole",
    title: "Что такое вонголе (морской петушок): редкий деликатес с Сахалина",
    description: "Подробно про вонголе: что за моллюск, откуда такое название, где его ловят на Сахалине и чем он полезен.",
    date: "2026-04-10",
    image: "/src/assets/blog-vongole-real-1.jpg",
    routePath: "/blog/chto-takoe-vongole",
  },
  {
    slug: "kak-prigotovit-vongole",
    title: "Как приготовить вонголе дома: простые рецепты с сахалинским уловом",
    description: "Готовим вонголе на домашней кухне. Советы по очистке, хранению и красивой подаче.",
    date: "2026-04-10",
    image: "/src/assets/blog-vongole-real-2.jpg",
    routePath: "/blog/kak-prigotovit-vongole",
  },
  {
    slug: "pasta-s-vongole",
    title: "Паста с вонголе: классический рецепт с сахалинскими моллюсками",
    description: "Тот самый итальянский Spaghetti alle Vongole из свежего сахалинского улова. Инструкция с фото.",
    date: "2026-04-10",
    image: "/src/assets/blog-vongole-real-3.jpg",
    routePath: "/blog/pasta-s-vongole",
  },
  {
    slug: "kak-vybrat-vongole",
    title: "Как выбрать свежие вонголе: советы от команды Ракушка65",
    description: "На что смотреть при покупке живых вонголе, как определить качество и правильно хранить.",
    date: "2026-04-10",
    image: "/src/assets/blog-vongole-real-4.jpg",
    routePath: "/blog/kak-vybrat-vongole",
  },
  {
    slug: "vongole-kak-v-restorane",
    title: "Вонголе как в ресторане: готовим сахалинский деликатес дома",
    description: "Секреты ресторанной подачи вонголе в обычных домашних условиях.",
    date: "2026-04-10",
    image: "/src/assets/blog-vongole-real-5.jpg",
    routePath: "/blog/vongole-kak-v-restorane",
  },
  {
    slug: "polza-vongole",
    title: "Польза вонголе: состав и свойства сахалинских моллюсков",
    description: "Чем полезны вонголе: витамины B12, железо, омега-3. Разбираем пищевую ценность морского петушка.",
    date: "2026-04-12",
    image: "/src/assets/blog-vongole-real-6.jpg",
    routePath: "/blog/polza-vongole",
  },
  {
    slug: "kak-hranit-vongole",
    title: "Как хранить вонголе: правила для живых моллюсков с Сахалина",
    description: "Инструкция по хранению живых вонголе дома: температура, время и подготовка к готовке.",
    date: "2026-04-12",
    image: "/src/assets/blog-vongole-storage.jpg",
    routePath: "/blog/kak-hranit-vongole",
  },
  // === Спизула ===
  {
    slug: "spisula-sahalinskaya",
    title: "Спизула сахалинская: что это за моллюск и почему он популярен",
    description: "Гид по сахалинской спизуле: вкус, текстура, способы готовки и чем она отличается от других.",
    date: "2026-04-12",
    image: "/src/assets/blog-spisula-beach.jpg",
    routePath: "/blog/spisula-sahalinskaya",
  },
  {
    slug: "kak-prigotovit-spisulu",
    title: "Как приготовить спизулу сахалинскую: техники и рецепты",
    description: "Пошаговые способы: сашими, гриль, суп или жарка в воке. Раскрываем вкус моллюска.",
    date: "2026-04-12",
    image: "/src/assets/blog-spisula-ice.jpg",
    routePath: "/blog/kak-prigotovit-spisulu",
  },
  {
    slug: "spisula-vs-vongole",
    title: "Спизула против вонголе: чем отличаются сахалинские моллюски",
    description: "Сравниваем вкус, текстуру, размер и способы приготовления двух популярных ракушек.",
    date: "2026-04-12",
    image: "/src/assets/blog-spisula-plated.jpg",
    routePath: "/blog/spisula-vs-vongole",
  },
  // === Устрицы ===
  {
    slug: "ustritsy-sahalin",
    title: "Сахалинские устрицы: вкус, польза и особенности",
    description: "Всё про наши устрицы: виды, вкус, польза и почему сахалинский улов считается эталонным.",
    date: "2026-04-11",
    image: "/src/assets/blog-oysters-real-1.jpg",
    routePath: "/blog/ustritsy-sahalin",
  },
  {
    slug: "kak-vybrat-ustritsy",
    title: "Как выбрать свежие устрицы: советы от Ракушка65",
    description: "Как отличить живую устрицу от несвежей, на что смотреть и как правильно хранить покупку.",
    date: "2026-04-11",
    image: "/src/assets/blog-oysters-real-2.jpg",
    routePath: "/blog/kak-vybrat-ustritsy",
  },
  {
    slug: "kak-otkryt-ustritsu",
    title: "Как открыть устрицу дома: простая инструкция",
    description: "Пошаговый гид по правильному вскрытию устриц в домашних условиях без лишних усилий.",
    date: "2026-04-11",
    image: "/src/assets/blog-oysters-real-3.jpg",
    routePath: "/blog/kak-otkryt-ustritsu",
  },
  {
    slug: "retsepty-s-ustritsami",
    title: "Рецепты с устрицами: готовим сахалинский улов дома",
    description: "Лучшие идеи: запеченные устрицы, в кляре, супы и традиционная подача на льду.",
    date: "2026-04-11",
    image: "/src/assets/blog-oysters-real-4.jpg",
    routePath: "/blog/retsepty-s-ustritsami",
  },
  // === Трепанг ===
  {
    slug: "trepang-sahalinskij",
    title: "Дальневосточный трепанг: что это за морской женьшень",
    description: "Гид по трепангу: где обитает на Сахалине, из чего состоит и чем полезен этот необычный продукт.",
    date: "2026-04-24",
    image: "/src/assets/blog-trepang-fresh.jpg",
    routePath: "/blog/trepang-sahalinskij",
  },
  {
    slug: "nastojka-na-trepange-recept",
    title: "Настойка на трепанге: классический рецепт с мёдом",
    description: "Готовим настойку дома: пропорции, технология и как правильно принимать этот сахалинский эликсир.",
    date: "2026-04-24",
    image: "/src/assets/blog-trepang-tincture-pour.jpg",
    routePath: "/blog/nastojka-na-trepange-recept",
  },
  {
    slug: "trepang-primenenie",
    title: "Применение трепанга: польза и важные противопоказания",
    description: "Влияние трепанга на иммунитет и сердце. Разбираем состав, схемы приема и на что обратить внимание.",
    date: "2026-04-24",
    image: "/src/assets/blog-trepang-honey.jpg",
    routePath: "/blog/trepang-primenenie",
  },
  {
    slug: "medovaya-nastojka-trepanga",
    title: "Медовая настойка с трепангом без спирта: рецепт и польза",
    description: "Безалкогольный вариант эликсира: как приготовить, как пить и чем полезна для иммунитета.",
    date: "2026-04-25",
    image: "/src/assets/blog-trepang-honey-tincture.jpg",
    routePath: "/blog/medovaya-nastojka-trepanga",
    productTag: "trepang-tincture" as ProductTag,
  },
].map((a): BlogArticle => ({ ...a, productTag: a.productTag ?? detectProductTag(a.slug) }));
